services:
  api:
    # Nutze lokalen Build aus der Basis-Compose, falls GHCR_IMAGE nicht korrekt gesetzt ist
    environment:
      - NODE_ENV=production
    # Production-Start (explizit, deckungsgleich mit Dockerfile-CMD)
    entrypoint: ["/bin/sh", "-lc"]
    command: ["npm run backend"]
    # Best practice: Container sollte Production-Build aus Dockerfile nutzen
    # Falls der Dockerfile nicht baut, fallback auf CMD:
    # command: ["sh", "-lc", "npm ci --omit=dev && npm run build && npm run start"]

  client:
    # Build client using multi-stage Dockerfile 'prod' target (nginx)
    build:
      context: ./sigmacode_ai/client
      dockerfile: Dockerfile
      target: prod
    image: sigmacode-ai/client:prod
    environment:
      # In production, prefer relative API path via reverse proxy
      - VITE_API_TARGET=${VITE_API_TARGET:-/api}
    ports:
      - "3093:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-lc", "wget -qO- http://localhost/ || curl -sf http://localhost/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  mongodb:
    # In Prod meist kein Port-Expose nötig; hier bewusst weggelassen

  meilisearch:
    # Prod: Port-Expose optional (z.B. nur intern über API)
