name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build client (CI)
        run: pnpm run frontend:ci

      - name: Run unit tests (client)
        run: pnpm run test:client || echo "no client tests configured"

      - name: Run unit tests (api)
        run: pnpm run test:api || echo "no api tests configured"
